# Generated by Django 5.2.8 on 2025-11-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_conversa_atendente_atual_conversa_bloquear_ia_and_more'),
        ('origens', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Razão social ou nome fantasia', max_length=200, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da empresa (opcional, formato: 00.000.000/0000-00)', max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('plano', models.CharField(choices=[('basico', 'Plano Básico'), ('profissional', 'Plano Profissional'), ('empresarial', 'Plano Empresarial'), ('trial', 'Trial')], default='trial', help_text='Plano de assinatura da empresa', max_length=20, verbose_name='Plano')),
                ('ativo', models.BooleanField(default=True, help_text='Empresas inativas não podem acessar o sistema', verbose_name='Empresa Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'usuarios_empresa',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='papel',
            field=models.CharField(choices=[('direcao', 'Direção'), ('comercial', 'Comercial'), ('administrativo', 'Administrativo'), ('admin', 'Administrador (Legado)'), ('atendimento', 'Atendimento (Legado)'), ('financeiro', 'Financeiro (Legado)')], default='comercial', max_length=20, verbose_name='Papel no sistema'),
        ),
        migrations.AddField(
            model_name='user',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa à qual o usuário pertence', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.empresa', verbose_name='Empresa'),
        ),
        migrations.CreateModel(
            name='PermissaoOrigemUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_ver', models.BooleanField(default=True, help_text='Se True, usuário pode ver leads desta origem', verbose_name='Pode Visualizar')),
                ('pode_editar', models.BooleanField(default=False, help_text='Se True, usuário pode editar/excluir leads desta origem', verbose_name='Pode Editar')),
                ('pode_atribuir', models.BooleanField(default=False, help_text='Se True, usuário pode atribuir leads desta origem para outros usuários', verbose_name='Pode Atribuir')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('fonte_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_usuario', to='origens.fonteorigem', verbose_name='Fonte de Origem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_origem', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Origem',
                'verbose_name_plural': 'Permissões de Origem',
                'db_table': 'usuarios_permissao_origem',
                'unique_together': {('user', 'fonte_origem')},
            },
        ),
        migrations.CreateModel(
            name='PermissaoSetorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_atender', models.BooleanField(default=True, help_text='Se True, usuário pode assumir e responder conversas deste setor', verbose_name='Pode Atender')),
                ('pode_visualizar', models.BooleanField(default=True, help_text='Se True, usuário pode visualizar conversas deste setor', verbose_name='Pode Visualizar')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('setor_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_usuario', to='atendimentos.setoratendimento', verbose_name='Setor de Atendimento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_setor', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Permissão de Setor',
                'verbose_name_plural': 'Permissões de Setor',
                'db_table': 'usuarios_permissao_setor',
                'unique_together': {('user', 'setor_atendimento')},
            },
        ),
    ]
