# Generated by Django 5.2.8 on 2025-11-19 18:42

from django.db import migrations


def criar_empresa_padrao(apps, schema_editor):
    """
    FASE 2: Data Migration - Cria empresa padrão para migração de dados

    Cria uma empresa chamada "Empresa Padrão" que será usada para
    popular o campo empresa em todos os registros existentes.
    """
    Empresa = apps.get_model('usuarios', 'Empresa')

    # Verifica se já existe uma empresa padrão
    empresa_padrao = Empresa.objects.filter(nome="Empresa Padrão").first()

    if not empresa_padrao:
        # Cria empresa padrão
        empresa_padrao = Empresa.objects.create(
            nome="Empresa Padrão",
            plano="basico",
            ativo=True
        )
        print(f"[OK] Empresa Padrao criada com ID: {empresa_padrao.id}")
    else:
        print(f"[OK] Empresa Padrao ja existe com ID: {empresa_padrao.id}")


def reverter_empresa_padrao(apps, schema_editor):
    """Reverte a criação da empresa padrão"""
    Empresa = apps.get_model('usuarios', 'Empresa')
    Empresa.objects.filter(nome="Empresa Padrão").delete()
    print("[REVERT] Empresa Padrao removida")


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa_alter_user_papel_user_empresa_and_more'),
    ]

    operations = [
        migrations.RunPython(criar_empresa_padrao, reverter_empresa_padrao),
    ]
