# Generated by Django 5.2.8 on 2025-11-19 02:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Setor')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal (ex: #3B82F6)', max_length=7)),
                ('horario_funcionamento', models.JSONField(blank=True, default=dict, help_text='Horário de funcionamento do setor em formato JSON', verbose_name='Horário de Funcionamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendentes', models.ManyToManyField(blank=True, related_name='setores_atendimento', to=settings.AUTH_USER_MODEL, verbose_name='Atendentes')),
            ],
            options={
                'verbose_name': 'Setor de Atendimento',
                'verbose_name_plural': 'Setores de Atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RespostaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('atalho', models.CharField(help_text='Atalho para usar a resposta (ex: /saudacao)', max_length=50, unique=True, verbose_name='Atalho')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem com Texto'), ('DOCUMENTO', 'Documento'), ('BOTOES', 'Botões'), ('LISTA', 'Lista')], default='TEXTO', max_length=20, verbose_name='Tipo')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('midia_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Opções para botões ou lista', verbose_name='Opções')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('contador_uso', models.IntegerField(default=0, verbose_name='Contador de Uso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_rapidas', to='atendimentos.setoratendimento', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Resposta Rápida',
                'verbose_name_plural': 'Respostas Rápidas',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('numero_telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Use formato internacional.', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='Número do WhatsApp')),
                ('instance_name', models.CharField(help_text='Nome da instância na Evolution API', max_length=100, unique=True, verbose_name='Nome da Instância (Evolution API)')),
                ('api_key', models.CharField(help_text='API Key da Evolution API', max_length=255, verbose_name='API Key')),
                ('api_url', models.URLField(default='https://api.evolution.com.br', help_text='URL base da Evolution API', verbose_name='URL da API')),
                ('status', models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado'), ('CONECTANDO', 'Conectando'), ('ERRO', 'Erro')], default='DESCONECTADO', max_length=20, verbose_name='Status')),
                ('qr_code', models.TextField(blank=True, help_text='QR Code para conexão (base64)', null=True, verbose_name='QR Code')),
                ('ultima_conexao', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexão')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('webhook_url', models.URLField(blank=True, help_text='URL para receber webhooks da Evolution API', null=True, verbose_name='Webhook URL')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='atendimentos.setoratendimento', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Dispositivo WhatsApp',
                'verbose_name_plural': 'Dispositivos WhatsApp',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(help_text='ID do chat no WhatsApp', max_length=100, verbose_name='Chat ID')),
                ('numero_cliente', models.CharField(max_length=20, verbose_name='Número do Cliente')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Atendimento'), ('EM_ATENDIMENTO', 'Em Atendimento'), ('RESOLVIDO', 'Resolvido'), ('FECHADO', 'Fechado')], default='AGUARDANDO', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridade')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Atendimento')),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('assunto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('nota_interna', models.TextField(blank=True, null=True, verbose_name='Nota Interna')),
                ('avaliacao', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Avaliação de 1 a 5', null=True, verbose_name='Avaliação')),
                ('comentario_avaliacao', models.TextField(blank=True, null=True, verbose_name='Comentário da Avaliação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atendente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendente')),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='clientes.contato', verbose_name='Contato')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversas', to='atendimentos.dispositivowhatsapp', verbose_name='Dispositivo WhatsApp')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversas', to='atendimentos.setoratendimento', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('midia_url', models.URLField(blank=True, null=True, verbose_name='URL da Mídia')),
                ('filtro_destinatarios', models.JSONField(blank=True, default=dict, help_text='Filtros aplicados para seleção de destinatários', verbose_name='Filtro de Destinatários')),
                ('data_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Agendamento')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('intervalo_envio', models.IntegerField(default=2, help_text='Intervalo em segundos entre cada envio', verbose_name='Intervalo de Envio (segundos)')),
                ('mensagens_por_minuto', models.IntegerField(default=20, help_text='Limite de mensagens por minuto', verbose_name='Mensagens por Minuto')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGENDADA', 'Agendada'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('PAUSADA', 'Pausada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('total_destinatarios', models.IntegerField(default=0, verbose_name='Total de Destinatários')),
                ('total_enviadas', models.IntegerField(default=0, verbose_name='Total Enviadas')),
                ('total_entregues', models.IntegerField(default=0, verbose_name='Total Entregues')),
                ('total_lidas', models.IntegerField(default=0, verbose_name='Total Lidas')),
                ('total_erros', models.IntegerField(default=0, verbose_name='Total de Erros')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('destinatarios', models.ManyToManyField(related_name='campanhas_recebidas', to='clientes.contato', verbose_name='Destinatários')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanhas', to='atendimentos.dispositivowhatsapp', verbose_name='Dispositivo WhatsApp')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanhas', to='atendimentos.setoratendimento', verbose_name='Setor')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(help_text='ID da mensagem no WhatsApp', max_length=100, unique=True, verbose_name='Message ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo'), ('AUDIO', 'Áudio'), ('DOCUMENTO', 'Documento'), ('LOCALIZACAO', 'Localização'), ('CONTATO', 'Contato'), ('STICKER', 'Sticker')], default='TEXTO', max_length=20, verbose_name='Tipo')),
                ('direcao', models.CharField(choices=[('RECEBIDA', 'Recebida'), ('ENVIADA', 'Enviada')], max_length=10, verbose_name='Direção')),
                ('status', models.CharField(choices=[('ENVIANDO', 'Enviando'), ('ENVIADA', 'Enviada'), ('ENTREGUE', 'Entregue'), ('LIDA', 'Lida'), ('ERRO', 'Erro')], default='ENVIANDO', max_length=10, verbose_name='Status')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('midia_url', models.URLField(blank=True, help_text='URL da mídia anexada', null=True, verbose_name='URL da Mídia')),
                ('midia_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo')),
                ('midia_mimetype', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais da mensagem', verbose_name='Metadados')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('agendada', models.BooleanField(default=False, verbose_name='Agendada')),
                ('data_agendamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Agendamento')),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='atendimentos.conversa', verbose_name='Conversa')),
                ('mensagem_respondida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='atendimentos.mensagem', verbose_name='Mensagem Respondida')),
                ('remetente', models.ForeignKey(blank=True, help_text='Preenchido apenas para mensagens enviadas por usuários', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente (Usuário)')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['data_envio'],
                'indexes': [models.Index(fields=['conversa', 'data_envio'], name='atendimento_convers_46f052_idx'), models.Index(fields=['message_id'], name='atendimento_message_6336cb_idx'), models.Index(fields=['status'], name='atendimento_status_9a6670_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['status', '-criado_em'], name='atendimento_status_955bad_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['chat_id'], name='atendimento_chat_id_e8276a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversa',
            index=models.Index(fields=['atendente', 'status'], name='atendimento_atenden_d7fb90_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversa',
            unique_together={('dispositivo', 'chat_id')},
        ),
        migrations.AddIndex(
            model_name='campanha',
            index=models.Index(fields=['status', '-criado_em'], name='atendimento_status_ee1847_idx'),
        ),
    ]
