# Generated by Django 5.2.8 on 2025-11-19 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivowhatsapp',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='dispositivowhatsapp',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='dispositivowhatsapp',
            name='instance_name',
        ),
        migrations.RemoveField(
            model_name='dispositivowhatsapp',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='access_token',
            field=models.CharField(default='', help_text='Token de acesso permanente da WhatsApp Business API', max_length=500, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='business_account_id',
            field=models.CharField(default='', help_text='ID da conta WhatsApp Business', max_length=100, verbose_name='Business Account ID'),
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='conversas_usadas_mes',
            field=models.IntegerField(default=0, verbose_name='Conversas Usadas no Mês'),
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='limite_mensal_conversas',
            field=models.IntegerField(default=1000, help_text='Limite de conversas gratuitas por mês', verbose_name='Limite Mensal de Conversas'),
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='phone_number_id',
            field=models.CharField(default='', help_text='ID do número de telefone na WhatsApp Business API', max_length=100, unique=True, verbose_name='Phone Number ID'),
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='ultima_verificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Verificação de Status'),
        ),
        migrations.AddField(
            model_name='dispositivowhatsapp',
            name='webhook_verify_token',
            field=models.CharField(blank=True, help_text='Token para verificação do webhook', max_length=255, null=True, verbose_name='Webhook Verify Token'),
        ),
        migrations.AlterField(
            model_name='dispositivowhatsapp',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL para receber webhooks da WhatsApp Business API', null=True, verbose_name='Webhook URL'),
        ),
        migrations.AddIndex(
            model_name='dispositivowhatsapp',
            index=models.Index(fields=['phone_number_id'], name='atendimento_phone_n_293281_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivowhatsapp',
            index=models.Index(fields=['business_account_id'], name='atendimento_busines_f1a4e7_idx'),
        ),
    ]
