# Generated by Django 5.2.8 on 2025-11-19 02:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Canal')),
                ('tipo', models.CharField(choices=[('WEBSITE', 'Website'), ('REDES_SOCIAIS', 'Redes Sociais'), ('EMAIL', 'E-mail Marketing'), ('TELEFONE', 'Telefone'), ('INDICACAO', 'Indicação'), ('EVENTO', 'Evento'), ('PUBLICIDADE', 'Publicidade Paga'), ('ORGANICO', 'Busca Orgânica'), ('DIRETO', 'Acesso Direto'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Tipo de Canal')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal para identificação visual (ex: #3B82F6)', max_length=7)),
                ('icone', models.CharField(blank=True, help_text='Nome do ícone (ex: facebook, google, email)', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('url_rastreamento', models.URLField(blank=True, help_text='URL base para rastreamento (ex: utm_source)', null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL de Rastreamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canais_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Canal de Origem',
                'verbose_name_plural': 'Canais de Origem',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FonteOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Fonte')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('codigo_rastreamento', models.CharField(blank=True, help_text='Código único para rastreamento (ex: utm_campaign)', max_length=100, null=True, verbose_name='Código de Rastreamento')),
                ('url_destino', models.URLField(blank=True, help_text='URL de destino/landing page', null=True, validators=[django.core.validators.URLValidator()], verbose_name='URL de Destino')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Total Investido')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Término')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes', to='origens.canalorigem', verbose_name='Canal')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fontes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Fonte de Origem',
                'verbose_name_plural': 'Fontes de Origem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origem')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent (Navegador)')),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Campaign')),
                ('utm_term', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Term')),
                ('utm_content', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTM Content')),
                ('url_referencia', models.URLField(blank=True, null=True, verbose_name='URL de Referência')),
                ('url_destino', models.URLField(blank=True, null=True, verbose_name='URL de Destino/Landing Page')),
                ('convertido', models.BooleanField(default=False, help_text='Indica se o lead foi convertido em cliente', verbose_name='Convertido em Cliente')),
                ('data_conversao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Conversão')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('contato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origens_registradas', to='clientes.contato', verbose_name='Contato Associado')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='origens.fonteorigem', verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Registro de Origem',
                'verbose_name_plural': 'Registros de Origem',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='canalorigem',
            index=models.Index(fields=['tipo'], name='origens_can_tipo_66890c_idx'),
        ),
        migrations.AddIndex(
            model_name='canalorigem',
            index=models.Index(fields=['ativo'], name='origens_can_ativo_2dc05f_idx'),
        ),
        migrations.AddIndex(
            model_name='fonteorigem',
            index=models.Index(fields=['canal', 'ativo'], name='origens_fon_canal_i_993510_idx'),
        ),
        migrations.AddIndex(
            model_name='fonteorigem',
            index=models.Index(fields=['codigo_rastreamento'], name='origens_fon_codigo__6c9b73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fonteorigem',
            unique_together={('canal', 'nome')},
        ),
        migrations.AddIndex(
            model_name='registroorigem',
            index=models.Index(fields=['fonte', '-data_registro'], name='origens_reg_fonte_i_8f4633_idx'),
        ),
        migrations.AddIndex(
            model_name='registroorigem',
            index=models.Index(fields=['contato'], name='origens_reg_contato_4737cc_idx'),
        ),
        migrations.AddIndex(
            model_name='registroorigem',
            index=models.Index(fields=['convertido'], name='origens_reg_convert_4776b0_idx'),
        ),
        migrations.AddIndex(
            model_name='registroorigem',
            index=models.Index(fields=['utm_source', 'utm_campaign'], name='origens_reg_utm_sou_b7887b_idx'),
        ),
    ]
