# Generated by Django 5.2.8 on 2025-11-19 01:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no funil')),
                ('cor', models.CharField(default='#3B82F6', help_text='Cor em hexadecimal (ex: #3B82F6)', max_length=7)),
                ('etapa_inicial', models.BooleanField(default=False, verbose_name='Etapa Inicial')),
                ('etapa_final_ganho', models.BooleanField(default=False, verbose_name='Etapa de Ganho')),
                ('etapa_final_perdido', models.BooleanField(default=False, verbose_name='Etapa de Perda')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome/Razão Social')),
                ('tipo_pessoa', models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='CPF ou CNPJ inválido', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$|^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$|^\\d{11}$|^\\d{14}$')], verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PROSPECTO', 'Prospecto')], default='PROSPECTO', max_length=20)),
                ('origem', models.CharField(blank=True, help_text='Como o cliente chegou até nós', max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Negócio')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Estimado')),
                ('probabilidade', models.IntegerField(default=50, help_text='Probabilidade de fechamento (0-100)', verbose_name='Probabilidade (%)')),
                ('valor_ponderado', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Valor Ponderado')),
                ('data_prevista_fechamento', models.DateField(blank=True, null=True, verbose_name='Data Prevista de Fechamento')),
                ('data_fechamento_real', models.DateField(blank=True, null=True, verbose_name='Data Real de Fechamento')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('GANHO', 'Ganho'), ('PERDIDO', 'Perdido')], default='ABERTO', max_length=20)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('motivo_perda', models.TextField(blank=True, help_text='Preencher caso o negócio seja perdido', null=True, verbose_name='Motivo da Perda')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='clientes.contato', verbose_name='Contato')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='negocios', to='clientes.pipeline', verbose_name='Etapa do Pipeline')),
            ],
            options={
                'verbose_name': 'Negócio',
                'verbose_name_plural': 'Negócios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('MUDANCA_PIPELINE', 'Mudança de Pipeline'), ('MUDANCA_VALOR', 'Mudança de Valor'), ('MUDANCA_STATUS', 'Mudança de Status'), ('MUDANCA_RESPONSAVEL', 'Mudança de Responsável'), ('ATUALIZACAO', 'Atualização'), ('OBSERVACAO', 'Observação')], max_length=30)),
                ('campo_alterado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_novo', models.TextField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.negocio', verbose_name='Negócio')),
            ],
            options={
                'verbose_name': 'Histórico do Negócio',
                'verbose_name_plural': 'Históricos dos Negócios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['nome'], name='clientes_co_nome_ac887a_idx'),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['email'], name='clientes_co_email_809b18_idx'),
        ),
        migrations.AddIndex(
            model_name='contato',
            index=models.Index(fields=['status'], name='clientes_co_status_4e5484_idx'),
        ),
        migrations.AddIndex(
            model_name='historiconegocio',
            index=models.Index(fields=['negocio', '-criado_em'], name='clientes_hi_negocio_2eb22b_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['status'], name='clientes_ne_status_ca66c4_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['pipeline'], name='clientes_ne_pipelin_5ad380_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['contato'], name='clientes_ne_contato_ef1ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['data_prevista_fechamento'], name='clientes_ne_data_pr_2d8e05_idx'),
        ),
    ]
